// Inlines every locale JSON into a single bundler-agnostic ESM module.
// Output: dist/index.js (exports `resources`, `supportedLngs`, `namespaces`)
//         dist/index.d.ts (hand-rolled types kept in sync with the shape below)
//
// Why inline instead of JSON imports: import assertions / JSON module resolution
// differ across Vite (frontend) and Metro (mobile). A plain JS object literal
// just works in both, with no consumer bundler config.
import { readFileSync, readdirSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const localesDir = join(root, "locales");
const langs = ["en", "es", "pt"];

const resources = {};
const namespaceSet = new Set();

for (const lang of langs) {
  resources[lang] = {};
  // per-namespace files: locales/<lang>/<namespace>.json
  const langDir = join(localesDir, lang);
  for (const file of readdirSync(langDir)) {
    if (!file.endsWith(".json")) continue;
    const ns = file.replace(/\.json$/, "");
    resources[lang][ns] = JSON.parse(readFileSync(join(langDir, file), "utf8"));
    namespaceSet.add(ns);
  }
  // mobile app's own files: locales/mobile/<lang>/<name>.json -> namespace "mobile_<name>"
  const mobileLangDir = join(localesDir, "mobile", lang);
  if (existsSync(mobileLangDir)) {
    for (const file of readdirSync(mobileLangDir)) {
      if (!file.endsWith(".json")) continue;
      const ns = `mobile_${file.replace(/\.json$/, "")}`;
      resources[lang][ns] = JSON.parse(readFileSync(join(mobileLangDir, file), "utf8"));
      namespaceSet.add(ns);
    }
  }
}

const namespaces = [...namespaceSet].sort();
const distDir = join(root, "dist");
mkdirSync(distDir, { recursive: true });

const banner = "// AUTO-GENERATED by scripts/build.mjs. Do not edit. Edit locales/**/*.json instead.\n";
writeFileSync(
  join(distDir, "index.js"),
  banner +
    `export const supportedLngs = ${JSON.stringify(langs)};\n` +
    `export const namespaces = ${JSON.stringify(namespaces)};\n` +
    `export const resources = ${JSON.stringify(resources)};\n` +
    `export default resources;\n`
);

writeFileSync(
  join(distDir, "index.d.ts"),
  banner +
    `export declare const supportedLngs: readonly ["en", "es", "pt"];\n` +
    `export declare const namespaces: readonly string[];\n` +
    `export type Lang = (typeof supportedLngs)[number];\n` +
    `export type Resources = Record<Lang, Record<string, Record<string, unknown>>>;\n` +
    `export declare const resources: Resources;\n` +
    `export default resources;\n`
);

console.log(
  `built dist/index.js: ${langs.length} langs x ${namespaces.length} namespaces (${namespaces.join(", ")})`
);
